### ISSUE TITLE
在 test 环境下 quarkus 的 hot reload 会出现连接出错导致 quarkus 启动失败

### ISSUE THREAD

**Issue by kenyonduan** [wppurking/hutch-java#5]

**Comment by wppurking** [comment]
暂时还没有找到这个问题的具体原因...

**Comment by wppurking** [comment]
检查 https://quarkus.io/guides/writing-extensions#integrating-with-development-mode

为插件添加 https://quarkus.io/guides/writing-extensions#testing-hot-reload 相关的测试, 确保 dev 环境可以进行 hot reload

**Comment by wppurking** [comment]
找到连接的原因. 正确处理好 conn 与 channel 的打开与关闭来解决此问题.  v1.1.0 已经解决.
